import { React, useState, useEffect } from 'react'
import { Loader, Card, FormField } from '../components'

export default function Home() {
  const [loading, setLoading] = useState(true)
  const [allPosts, setAllPosts] = useState(null)

  return (
    <>
      <section className="max-w-7xl mx-auto ">
        <div>
          <h1 className="font-extrabold text-[#222328] text-[32px]">
            The Community Showcase
          </h1>
          <p className="mt-2 text-[#666e75] text-[16px] max-w-[500px]">
            Browse the collection of visual creations generated by DALL-E AI
          </p>
        </div>
        <div className="mt-16">
          <FormField />
          <div className="mt-10">
            {loading ? (
              <div className="flex justify-center items-center">
                <Loader />
              </div>
            ) : (
              <></>
            )}
          </div>
        </div>
      </section>
    </>
  )
}
